sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDKjUUrXWkb9EnNLKNy
    access-key-secret: dkkBBZvRFTxQKQ3ViRwy04EQ7Mk5cw
    bucket-name: sky-itcast-8080
  redis:
    host: localhost
    port: 6379
#    password:
    database: 10
  wechat:
    appid: wx80170c6641064f37
    secret: d53a0d62c847e8b3658ff8b212c095c0
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
